import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getCountries, getUser } from "./(home)/_actions";
import { ClientProviders } from "./_components/client-providers";
import { Navbar } from "./_components/navbar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const [{ countries }, user] = await Promise.all([getCountries(), getUser()]);
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}
			>
				<ClientProviders>
					<div className="flex flex-col h-screen">
						<Navbar countries={countries} user={user} />
						{children}
					</div>
				</ClientProviders>
			</body>
		</html>
	);
}
